joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

ackermann_controller:
  type: ackermann_controller/AckermannController
  spinning_joints:
    - "ackermann_rear_axle"
  steering_joints:
    - "ackermann_steering_joint"
  odometry_joints:
    - "ackermann_rear_axle"

  required_drive_modes:
    ackermann_rear_axle: 3 #Rear axle will be in profile velocity mode according to CANopen standard
    ackermann_steering_joint: 1 #Steering axle will be in position mode according to CANopen standard

  pose_covariance_diagonal: [1.0,1.0,1.0,1.0,1.0,1.0]
  twist_covariance_diagonal: [1.0,1.0,1.0,1.0,1.0,1.0]

  has_velocity_limits: true
  has_acceleration_limits: true
  has_deceleration_limits: true
  has_jerk_limits: false
  max_velocity: 5.0
  #min_velocity: 0.0
  max_acceleration: 2.0
  #min_acceleration: 0.0
  max_deceleration: 2.0
  #min_deceleration: 0.0

  enable_odom_tf: false

  wheelbase: 1.206

  steering_angle_instead_of_angular_speed: true

  cmd_vel_timeout: 0.5

  base_model_link: "base_link"

  odom_frame_id: "odom"

  base_frame_id: "base_link"